# Generated by Django 6.0.1 on 2026-01-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motive',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
