# Generated by Django 6.0.1 on 2026-01-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0002_alter_motive_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='icon',
            field=models.ImageField(upload_to='locations/'),
        ),
        migrations.AlterField(
            model_name='motive',
            name='icon',
            field=models.ImageField(upload_to='motives/'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='icon',
            field=models.ImageField(upload_to='suspects/'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='icon',
            field=models.ImageField(upload_to='weapons/'),
        ),
    ]
